apiVersion: v1
clusters:
- cluster:
    certificate-authority: /path/to/your/ca.crt
    server: https://127.0.0.1:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /path/to/your/client.crt
    client-key: /path/to/your/client.key
