apiVersion: v1
kind: Pod
metadata:
  name: bitpin-db
spec:
  containers:
    - name: bitpin-db
      image: postgres:11-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: bitpin_usr
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_DB
          value: bitpin_db
      volumeMounts:
        - name: bitpin-postgres-data
          mountPath: /var/lib/postgresql/data
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - pg_isready -U bitpin_usr
        initialDelaySeconds: 5
        periodSeconds: 10
  volumes:
    - name: bitpin-postgres-data
      persistentVolumeClaim:
        claimName: bitpin-postgres-pvc
