apiVersion: v1
kind: Pod
metadata:
  name: pgadmin
spec:
  containers:
    - name: pgadmin
      image: dpage/pgadmin4
      ports:
        - containerPort: 80
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@ava.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
      volumeMounts:
        - name: pgadmin-volume
          mountPath: /root/.pgadmin
  volumes:
    - name: pgadmin-volume
      hostPath:
        path: /path/to/pgadmin
        type: Directory
